services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    ports:
      - 9000
    environment:
      - TZ=America/Santo_Domingo

volumes:
  portainer-data: {}